int16 robot_id
geometry_msgs/Point true_map_position
geometry_msgs/Point estimated_map_position
geometry_msgs/Point one_shot_map_position
float64 error_meters
float64[] covariance_meter_sq
float64[] true_range_bearing
float64[] est_range_bearing
float64 first_csi_measurement_timestamp
float64 nearest_timestamp_for_pose
float64[] filter_predicted_range_bearing
float64[] filter_residual_error_range_bearing
int16 status




